//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamilyMember()
        {
            this.FamilyMember1 = new HashSet<FamilyMember>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int HouseholdID { get; set; }
        public int GenderID { get; set; }
        public int MaritalStatusID { get; set; }
        public Nullable<int> SpouseID { get; set; }
        public int OccupationTypeID { get; set; }
        public decimal AnnualIncome { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Household Household { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual OccupationType OccupationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyMember> FamilyMember1 { get; set; }
        public virtual FamilyMember FamilyMember2 { get; set; }
    }
}
